### ISSUE TITLE
Error with "add limits to axes"

### ISSUE THREAD

**Issue by PierreJeunesse** [Attolab/pymodaq_plugins_zaber#4]
Hello, 

I have an issue using the Zaber plugin with a X_LHM150A Zaber stage.
According to the data logger it seems to come from "add limits to axes" function.
Please find in attachment more informations about the issue.

Best

[Plugin Python Zaber.pdf](https://github.com/Attolab/pymodaq_plugins_zaber/files/13298247/Plugin.Python.Zaber.pdf)

**Comment by rgeneaux** [comment]
Hi,
Thanks for the bug report !

Looking at your file, first we need to make sure that the plugin is installed in the right way.

From your screenshots, I see that you cloned the pymodaq_plugins_zaber repository onto your computer. **This is necessary only if you want to make changes to the plugin** (as a developer). When you clone a repo, it is not actually installed as a python package. To do so, you need to go in your pycharm terminal and type "pip install -e ." (the dot is not a typo). This will install the plugin in developer mode, so that all code changes are directly seen by pthon.

However, for most usages, you should go **the easier route**: simply type in your anaconda terminal "`pip install pymodaq_plugins_zaber`". This will fetch the last version, automatically install all required packages (like zaber_motion, which you installed by hand). This is the easy way, after that you should see Zaber as an option when you run daq_move.

To explain some details, when we install a package by doing `pip install somethingsomething`, it actually runs a script called setup.py, that will do everything for us - among which, install dependencies, and make the plugin visible by pymodaq (this would remove your "Zaber is an invalid actuator" error).

My suggestion: start from a clean environment (since you some copied files into other plugins - could be a mess) and try again!

That being said, there probably is a bug in v4.1.0 with multiaxes, I will look at it tomorrow!

**Comment by PierreJeunesse** [comment]
Hi,
Thanks for the complete answer. 

After "pip install pymodaq_plugins_zaber" I launched daq_move_Zaber from its location in the new environment:
C:\ProgramData\miniconda3\envs\pymo4_zaber\Lib\site-packages\pymodaq_plugins_zaber\daq_move_plugins.

It still shows the issue with "add limits to axes" and the "Stage uninitialized" message.
Please find in attachment the copy of the data logger.

Best

[231109Plugin Python Zaber.pdf](https://github.com/Attolab/pymodaq_plugins_zaber/files/13310494/231109Plugin.Python.Zaber.pdf)

**Comment by rgeneaux** [comment]
Hi Pierre,
Thanks! it looks like this is a bug with pymodaq when the number of axes is 1 (I didn't see it as my controller has 2). I raised the issue in https://github.com/PyMoDAQ/PyMoDAQ/issues/211 on the github pymodaq.

**Comment by rgeneaux** [comment]
Actually I realized that the line with the bug is not needed at all (it does nothing :-) )
so I patched it, can you upgrade your plugin to v 2.0.1 ( `pip install --upgrade pymodaq_plugins_zaber` ) and let me know if things are working fine for you?

**Comment by PierreJeunesse** [comment]
Hi, 
Everything works fine now, thank you very much!
For information, after upgrading the Zaber plugin to 2.0.1, I also did an update of conda and installed h5py ( `conda install h5py`) and adaptive ( `pip install adaptive`)
